Add banner for harvested dataset
etalab/udata-front pull request #73
Opened 2022-01-25 14:10 UTC by nicolaskempf57

Close https://github.com/etalab/data.gouv.fr/issues/657

2022-01-26 10:24 UTC, maudetes reviewed
The banner seems good to me.

However, I think that `remote_url` is actually only set for CKAN datasets. I'm not sure we can have one consistent value. I need to check that up. At worst, we can use `harvest:domain`.

2022-02-01 15:45 UTC, maudetes commented
> However, I think that `remote_url` is actually only set for CKAN datasets. I'm not sure we can have one consistent value. I need to check that up. At worst, we can use `harvest:domain`.

It is set for CKAN and ODS datasets but not for DCAT. But we should keep on using `remote_url` here and make sure it is set in DCAT in the backend.

2022-02-01 15:49 UTC, maudetes approved these changes
I think it's all good here ! :tractor:

2022-02-09 13:33 UTC, maudetes requested changes
After discussion, we need to change the background color, that seems like a warning. We will also change for a simple background and grid instead of the well for a better icon alignment.

2022-02-10 15:55 UTC, nicolaskempf57 commented
Banner background is now blue !

2022-02-14 14:20 UTC, maudetes commented on udata_front/theme/gouvfr/templates/dataset/display.html
> +            _("This dataset come from an external portal.
I think we're missing a space between the two phrases here
![image](https://user-images.githubusercontent.com/28541902/153881396-da437c4f-8307-4525-997b-44d245709cea.png)

2022-02-14 14:21 UTC, maudetes approved these changes

2022-02-15 08:48 UTC, merged